### ISSUE TITLE
most right screen fails to initialize - IPStube

### ISSUE THREAD

**Issue by Trigger-4622** [judge2005/EleksTubeIPS#24]
Installed firmware 1.6.2 from the web installer.
(As for my understanding the most recent 1.6.2).

The right most screen fails to initialize, in stock firmware it works just fine.
Images attached bellow.

Feel free to msg me ill try to pinpoint the issue with my hardware, Thank you so much for your effort with this firmware!

![20241214_184720](https://github.com/user-attachments/assets/51a53434-a65f-4da1-a8ca-714af4b0fda6)
![20241214_184719](https://github.com/user-attachments/assets/03391699-90bb-4feb-961a-c13865e45042)

**Comment by judge2005** [comment]
Well that's interesting as I don't think that firmware should work at all with this clock (I received my ipstube clock today and it didn't work with mine!). I've uploaded a new version to https://www.nixies.us/projects/elekstubeips-clock/elekstube-ips-v1-2-2/. I noticed that I have to put my clock in boot mode and that I can't configure the WiFi directly from the web page - I've updated the instructions accordingly. Let me know if this works.

**Comment by Trigger-4622** [comment]
Will give the new one a chance right now!
It took me quit a few tries to get it to work with any firmware at all. i dont know what changed but after a few tries it just worked... really strange.... 
If you want to have a look i found another guy who made a working firmware that initializes all of the screens, but its premature lacking features other than the clock and mqtt non the less awesome work too. 

Also.... I kind of received my clock with no firmware installed at all... any chance you could please upload a copy of the original firmware?

**Comment by Trigger-4622** [comment]
Well, just installed 1.6.3 and it woorks!
Just remembered, i reuploaded the bootloader, maybe it had somthing to do with it?
let me know if you need me to do anything to help with bug fixing, will be more than happy to!
![image_2024-12-14_193751578](https://github.com/user-attachments/assets/bfb9182c-eb25-42ce-bea2-865f895cab5f)

**Comment by judge2005** [comment]
I've attached my backup of the original firmware to this comment.

Kind of jealous of the underlighting!
[ipstube.bin.zip](https://github.com/user-attachments/files/18137048/ipstube.bin.zip)
